/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainTransactionsImport } from './routes/_main/transactions'
import { Route as MainDashboardImport } from './routes/_main/dashboard'
import { Route as MainChatImport } from './routes/_main/chat'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as MainDashboardIndexImport } from './routes/_main/dashboard/index'
import { Route as MainDashboardLoansImport } from './routes/_main/dashboard/loans'
import { Route as MainDashboardFileUploadImport } from './routes/_main/dashboard/file-upload'
import { Route as MainDashboardAddAccountImport } from './routes/_main/dashboard/add-account'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainTransactionsRoute = MainTransactionsImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any)

const MainDashboardRoute = MainDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)

const MainChatRoute = MainChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MainRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const MainDashboardIndexRoute = MainDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDashboardRoute,
} as any)

const MainDashboardLoansRoute = MainDashboardLoansImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => MainDashboardRoute,
} as any)

const MainDashboardFileUploadRoute = MainDashboardFileUploadImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => MainDashboardRoute,
} as any)

const MainDashboardAddAccountRoute = MainDashboardAddAccountImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => MainDashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_main/chat': {
      id: '/_main/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof MainChatImport
      parentRoute: typeof MainImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardImport
      parentRoute: typeof MainImport
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/dashboard/add-account': {
      id: '/_main/dashboard/add-account'
      path: '/add-account'
      fullPath: '/dashboard/add-account'
      preLoaderRoute: typeof MainDashboardAddAccountImport
      parentRoute: typeof MainDashboardImport
    }
    '/_main/dashboard/file-upload': {
      id: '/_main/dashboard/file-upload'
      path: '/file-upload'
      fullPath: '/dashboard/file-upload'
      preLoaderRoute: typeof MainDashboardFileUploadImport
      parentRoute: typeof MainDashboardImport
    }
    '/_main/dashboard/loans': {
      id: '/_main/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof MainDashboardLoansImport
      parentRoute: typeof MainDashboardImport
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof MainDashboardIndexImport
      parentRoute: typeof MainDashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainDashboardRouteChildren {
  MainDashboardAddAccountRoute: typeof MainDashboardAddAccountRoute
  MainDashboardFileUploadRoute: typeof MainDashboardFileUploadRoute
  MainDashboardLoansRoute: typeof MainDashboardLoansRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
}

const MainDashboardRouteChildren: MainDashboardRouteChildren = {
  MainDashboardAddAccountRoute: MainDashboardAddAccountRoute,
  MainDashboardFileUploadRoute: MainDashboardFileUploadRoute,
  MainDashboardLoansRoute: MainDashboardLoansRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
}

const MainDashboardRouteWithChildren = MainDashboardRoute._addFileChildren(
  MainDashboardRouteChildren,
)

interface MainRouteChildren {
  MainChatRoute: typeof MainChatRoute
  MainDashboardRoute: typeof MainDashboardRouteWithChildren
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainChatRoute: MainChatRoute,
  MainDashboardRoute: MainDashboardRouteWithChildren,
  MainTransactionsRoute: MainTransactionsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/chat': typeof MainChatRoute
  '/dashboard': typeof MainDashboardRouteWithChildren
  '/transactions': typeof MainTransactionsRoute
  '/': typeof MainIndexRoute
  '/dashboard/add-account': typeof MainDashboardAddAccountRoute
  '/dashboard/file-upload': typeof MainDashboardFileUploadRoute
  '/dashboard/loans': typeof MainDashboardLoansRoute
  '/dashboard/': typeof MainDashboardIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/chat': typeof MainChatRoute
  '/transactions': typeof MainTransactionsRoute
  '/': typeof MainIndexRoute
  '/dashboard/add-account': typeof MainDashboardAddAccountRoute
  '/dashboard/file-upload': typeof MainDashboardFileUploadRoute
  '/dashboard/loans': typeof MainDashboardLoansRoute
  '/dashboard': typeof MainDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/chat': typeof MainChatRoute
  '/_main/dashboard': typeof MainDashboardRouteWithChildren
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/dashboard/add-account': typeof MainDashboardAddAccountRoute
  '/_main/dashboard/file-upload': typeof MainDashboardFileUploadRoute
  '/_main/dashboard/loans': typeof MainDashboardLoansRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/transactions'
    | '/'
    | '/dashboard/add-account'
    | '/dashboard/file-upload'
    | '/dashboard/loans'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/signup'
    | '/chat'
    | '/transactions'
    | '/'
    | '/dashboard/add-account'
    | '/dashboard/file-upload'
    | '/dashboard/loans'
    | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_main/chat'
    | '/_main/dashboard'
    | '/_main/transactions'
    | '/_main/'
    | '/_main/dashboard/add-account'
    | '/_main/dashboard/file-upload'
    | '/_main/dashboard/loans'
    | '/_main/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/chat",
        "/_main/dashboard",
        "/_main/transactions",
        "/_main/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_main/chat": {
      "filePath": "_main/chat.tsx",
      "parent": "/_main"
    },
    "/_main/dashboard": {
      "filePath": "_main/dashboard.tsx",
      "parent": "/_main",
      "children": [
        "/_main/dashboard/add-account",
        "/_main/dashboard/file-upload",
        "/_main/dashboard/loans",
        "/_main/dashboard/"
      ]
    },
    "/_main/transactions": {
      "filePath": "_main/transactions.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/dashboard/add-account": {
      "filePath": "_main/dashboard/add-account.tsx",
      "parent": "/_main/dashboard"
    },
    "/_main/dashboard/file-upload": {
      "filePath": "_main/dashboard/file-upload.tsx",
      "parent": "/_main/dashboard"
    },
    "/_main/dashboard/loans": {
      "filePath": "_main/dashboard/loans.tsx",
      "parent": "/_main/dashboard"
    },
    "/_main/dashboard/": {
      "filePath": "_main/dashboard/index.tsx",
      "parent": "/_main/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
